# Generated by Django 3.2.9 on 2022-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description_com',
            field=models.CharField(blank=True, max_length=170),
        ),
    ]
