# Generated by Django 4.0 on 2022-02-01 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ad', models.ImageField(upload_to='photos/ad')),
                ('link', models.URLField(max_length=150)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_cat', models.ImageField(upload_to='photos/category')),
                ('name_cat', models.CharField(max_length=50)),
                ('desc_cat', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_com', models.ImageField(upload_to='photos/company')),
                ('name_com', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('desc_com', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=70)),
                ('city', models.CharField(choices=[('مكة', 'مكة'), ('الرياض', 'الرياض'), ('جدة', 'جدة'), ('المدينة المنورة', 'المدينة المنورة'), ('الدمام', 'الدمام'), ('الطائف', 'الطائف'), ('حائل', 'حائل'), ('ينبع', 'ينبع')], max_length=70)),
                ('phone', models.IntegerField()),
                ('website', models.URLField(max_length=150)),
                ('facebook_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('instgram_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('whatsapp_link', models.URLField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.category')),
            ],
        ),
    ]
