# Generated by Django 3.2.9 on 2022-02-01 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_ad_category_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo_cat',
            field=models.FileField(upload_to='photos/category', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
