# Generated by Django 3.2.9 on 2022-02-24 10:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_company_description_com'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_com', models.CharField(max_length=50)),
                ('category_com', models.CharField(default='none', max_length=50)),
                ('description_com', models.CharField(blank=True, max_length=170)),
                ('city', models.CharField(max_length=70)),
                ('location', models.CharField(blank=True, max_length=70)),
                ('phone_num', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, max_length=150)),
                ('facebook_link', models.URLField(blank=True, max_length=100)),
                ('twitter_link', models.URLField(blank=True, max_length=100)),
                ('instgram_link', models.URLField(blank=True, max_length=100)),
                ('linkedin_link', models.URLField(blank=True, max_length=100)),
                ('whatsapp_link', models.URLField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('review', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
