# Generated by Django 4.0 on 2022-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_company_category_com_alter_company_slug_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
