# Generated by Django 4.0 on 2022-02-01 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_ad_date_created_alter_category_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 12, 1, 1, 714263)),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 12, 1, 1, 712264)),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 12, 1, 1, 713263)),
        ),
    ]
