# Generated by Django 3.2.9 on 2022-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20220206_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug_com',
            field=models.CharField(choices=[('مكة', 'مكة'), ('الرياض', 'الرياض'), ('جدة', 'جدة'), ('المدينة المنورة', 'المدينة المنورة'), ('الدمام', 'الدمام'), ('الطائف', 'الطائف'), ('حائل', 'حائل'), ('ينبع', 'ينبع')], default='none', max_length=50),
        ),
    ]
