# Generated by Django 3.2.9 on 2022-02-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_company_slug_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug_com',
            field=models.CharField(choices=[('اعلام', 'media'), ('خالد', 'khalid')], default='none', max_length=50),
        ),
    ]
